### ISSUE TITLE
Example on the front page doesn't work

### ISSUE THREAD

**Issue by tepperly** [gverger/ruby-cbc#14]
I am evaluating the ruby-cbc gem on a Debian Unstable system.
Linux faerun 4.3.0-1-amd64 #1 SMP Debian 4.3.5-1 (2016-02-06) x86_64 GNU/Linux
$ ruby --version
ruby 2.3.3p222 (2016-11-21) [x86_64-linux-gnu]
I installed ruby-cbc and cbc-wrapper using "gem install ruby-cbc".
$ gem -list | grep cbc
cbc-wrapper (2.9.9.2)
ruby-cbc (0.3.16)

I tried running this script.
```ruby
#!/usr/bin/env ruby
require 'forwardable'
require 'ruby-cbc'
m = Cbc::Model.new
x1, x2, x3 = m.int_var_array(3, 0..Cbc::INF)

m.maximize(10 * x1 + 6 * x2 + 4 * x3)

m.enforce(x1 + x2 + x3 <= 100)
m.enforce(10 * x1 + 4 * x2 + 5 * x3 <= 600)
m.enforce(2 * x1 + 2 * x2 + 6* x3 <= 300)

p = m.to_problem

p.solve

if ! p.proven_infeasible?
  puts "x1 = #{p.value_of(x1)}"
  puts "x2 = #{p.value_of(x2)}"
  puts "x3 = #{p.value_of(x3)}"
end
```
The script is inspired by the example on the github.com page for ruby-cbc.  Without the require 
 'forwardable', I get this:
```sh
$ ruby cbctest.rb
/var/lib/gems/2.3.0/gems/ruby-cbc-0.3.16/lib/ruby-cbc/ilp/term_array.rb:3:in `<class:TermArray>': uninitialized constant Ilp::TermArray::Forwardable (NameError)
        from /var/lib/gems/2.3.0/gems/ruby-cbc-0.3.16/lib/ruby-cbc/ilp/term_array.rb:2:in `<module:Ilp>'
        from /var/lib/gems/2.3.0/gems/ruby-cbc-0.3.16/lib/ruby-cbc/ilp/term_array.rb:1:in `<top (required)>'
        from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /var/lib/gems/2.3.0/gems/ruby-cbc-0.3.16/lib/ruby-cbc.rb:21:in `block in <top (required)>'
        from /var/lib/gems/2.3.0/gems/ruby-cbc-0.3.16/lib/ruby-cbc.rb:20:in `each'
        from /var/lib/gems/2.3.0/gems/ruby-cbc-0.3.16/lib/ruby-cbc.rb:20:in `<top (required)>'
        from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:127:in `require'
```
Adding the `require 'forwardable'` resolves this issue; although, it seems to me that term_array.rb should have the require.
Running the script after fixing this issue yields:
```sh
$ ruby cbctest.rb
1 was provided for  - valid range is 0 to 0
1e+08 was provided for  - valid range is 0 to 0
5 was provided for  - valid range is 0 to 0
2147483647 was provided for  - valid range is 0 to 0
5 was provided for  - valid range is 0 to 0
1e-06 was provided for  - valid range is 0 to 0
1e-05 was provided for  - valid range is 0 to 0
-1 was provided for  - valid range is 0 to 0
1003 was provided for  - valid range is 0 to 0
1057 was provided for  - valid range is 0 to 0
1 was provided for  - valid range is 0 to 0
-1 was provided for  - valid range is 0 to 0
100 was provided for  - valid range is 0 to 0
2 was provided for  - valid range is 0 to 0
30 was provided for  - valid range is 0 to 0
1005043 was provided for  - valid range is 0 to 0
6 was provided for  - valid range is 0 to 0
Abort
```

**Comment by gverger** [comment]
Hello,
I have been able to reproduce it on an unstable debian. It seems to be coming from the `cbc-wrapper` gem.

Can you confirm you have the same?
```ruby
require "cbc-wrapper"
Cbc_wrapper.Cbc_newModel
# => Same range errors
```

I don't know where it is coming from, since it is supposed to only initialize the cbc model in the native library.

**Comment by gverger** [comment]
And by the way, I don't have it failing because of `Forwardable`, but you are right and I should require it.

**Comment by tepperly** [comment]
It's an issue with cbc-wrapper.
```sh
$ irb
irb(main):001:0> require "cbc-wrapper"
=> true
irb(main):002:0> Cbc_wrapper.Cbc_newModel
1 was provided for  - valid range is 0 to 0
1e+08 was provided for  - valid range is 0 to 0
5 was provided for  - valid range is 0 to 0
2147483647 was provided for  - valid range is 0 to 0
5 was provided for  - valid range is 0 to 0
1e-06 was provided for  - valid range is 0 to 0
1e-05 was provided for  - valid range is 0 to 0
-1 was provided for  - valid range is 0 to 0
1003 was provided for  - valid range is 0 to 0
1057 was provided for  - valid range is 0 to 0
1 was provided for  - valid range is 0 to 0
-1 was provided for  - valid range is 0 to 0
100 was provided for  - valid range is 0 to 0
=> #<SWIG::TYPE_p_void:0x005582e0fd5288 @__swigtype__="_p_void">
irb(main):003:0> 
```

**Comment by nurettin** [comment]
I had the same problem just now, `require "forwardable"` solved the issue for me.

**Comment by gverger** [comment]
Using version 2.9.9.3 of `cbc-wrapper` fixes this problem.
